encryption: change end_of_file_mark to a std::string
it turns out, in this case, Clang-17 is more picky than older versions
of Clang.

with Clang 17, we'd have following FTBFS:

```
ent/encryption/encryption.cc:636:41: error: invalid operands to binary expression ('std::string' (aka 'basic_string<char>') and 'const sstring' (aka 'const basic_sstring<char, unsigned in
t, 15>'))
                        } else if (line == end_of_file_mark) {
                                   ~~~~ ^  ~~~~~~~~~~~~~~~~
```

as we don't have `operator==(const std::string&, const std::sstring&)`
yet.

in this change, the type of `end_of_file_mark` is changed from `sstring`
to `std::string`, so `line` and `end_of_file_mark` can be compared.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

Closes #2660