cql3: check empty string with char(-1) not -1
this change addresses an issue where the empty password is logged
in the audit info by a scylla node deployed on an aarch64 machine.

on aarch64 platforms, unlike amd64 platforms, `char` is unsigned. so, if
we have something like
```c++
string s;
s.push_back(-1);
bool equals = s.back() == -1;
```
`equals` would be false, as, because the LHS and RHS of the comparision
statement are `unsigned char` and `signed int`, since the later has a
higher conversion rank, and is able to represent all values covered by
the former, when performing comparision the former is promoted to the
type of latter. so the value of `equals` would be "255 == -1", which
evaluates to `false`.

so, before this change, we always take an empty password as a non-empty
and escape it, and escaped string is still the signel char string:
char(-1). but we are supposed to replace the plain password with
"'***'", while the string to be matched fails to include the password,
so we are unable to replace the "empty" password with "***". this would
leak the sensitive information that the password is empty to the audit info.

after this change, `password` is kept empty if `raw_password` represents
an empty password, so, after escaping and replacing the password, as
expected, the password part in the query statement would be masked with
"***".

without this change the compiler would complain at this comparison
statement. to make this more correct, and silence the warning, let's
extract `is_empty_password()` helper out. and document it with
more comment.

also, this change silences following warning:

```
clang++ -MD -MT build/debug/cql3/statements/role-management-statements.o -MF build/debug/cql3/statements/role-management-statements.o.d -I/jenkins/workspace/scylla-enterprise/build/scylla/seastar/include -I/jenkins/workspace/scylla-enterprise/build/scylla/build/debug/seastar/gen/include -U_FORTIFY_SOURCE -Werror=unused-result -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_SCHEDULING_GROUPS_COUNT=18 -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_SHARED -I/usr/include/p11-kit-1   -ffile-prefix-map=/jenkins/workspace/scylla-enterprise/build/scylla=. -march=armv8-a+crc+crypto -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -O0 -DSCYLLA_BUILD_MODE=debug -g -gz -iquote. -iquote build/debug/gen --std=gnu++20  -ffile-prefix-map=/jenkins/workspace/scylla-enterprise/build/scylla=. -march=armv8-a+crc+crypto  -I/usr/include/p11-kit-1 -DBOOST_TEST_DYN_LINK   -DNOMINMAX -DNOMINMAX -fvisibility=hidden -Ikmipc/kmipc-2.1.0t-rhel84_aarch64/include -DHAVE_KMIP  -Wall -Werror -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-command-line-argument -Wno-unsupported-friend -Wno-implicit-int-float-conversion -Wno-psabi -Wno-narrowing -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN -DFMT_DEPRECATED_OSTREAM  -c -o build/debug/cql3/statements/role-management-statements.o cql3/statements/role-management-statements.cc
 cql3/statements/role-management-statements.cc:134:54: error: result of comparison of constant -1 with expression of type 'const char' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
     if ((raw_password.size() == 1 && raw_password[0] != -1) || raw_password.size() > 1) {
                                      ~~~~~~~~~~~~~~~ ^  ~~
 cql3/statements/role-management-statements.cc:153:36: error: result of comparison of constant -1 with expression of type 'const char' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
         if ((v.size() == 1 && v[0] != -1) || v.size() > 1) {
                               ~~~~ ^  ~~
```

Fixes #3450
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

Closes scylladb/scylla-enterprise#3451