pgo: fix python type annotation
As pointed out by mypy:

pgo/pgo.py:150: error: Incompatible return value type (got "list[Any]", expected "tuple[Any, ...]")  [return-value]
Found 1 error in 1 file (checked 1 source file)

(cherry picked from commit bfd3fb8403e2cfc0d77daff0dfe5e89567bdb99f)