cql3: do not include unused header
this change is not cherry-picked from OSS branch, as the change
which addresses this issue was actually already included:
76bea231743dc1736319421f71ca62ab67afb351. but part of it was
reverted by ce3454b37489c80cdad2587b38c42a28fccb31b2, which
brought the previously removed

```c++
```
back to this source file. hence the build failure like:

```
clang++ ... -c -o build/release/gen/cql3/CqlParser.o build/release/gen/cql3/CqlParser.cpp
In file included from build/release/gen/cql3/CqlParser.cpp:44:
In file included from build/release/gen/cql3/CqlParser.hpp:75:
In file included from ./cql3/statements/create_function_statement.hh:12:
In file included from ./cql3/functions/user_function.hh:16:
./lang/wasm.hh:15:10: fatal error: 'rust/wasmtime_bindings.hh' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

where we would otherwise need to add the build dependency from
`CqlParser.o` to `rust/wasmtime_bindings.hh`, which is generated
from `./rust/wasmtime_bindings/src/lib.rs`.

so, in this change, the `#include` is removed again to drop this
dependency. so we don't try our luck when building the tree, in
hope that `./rust/wasmtime_bindings/src/lib.rs` is processed by
cxxbridge before compiling `CqlParser.cc`.

Fixes #3022
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

Closes #3025