compaction: incremental_backlog_tracker: move implementation out of line
Header is not self-sufficient:
```
[2023-03-09T15:55:52.426Z] ./compaction/incremental_backlog_tracker.hh:37:71: error: member access into incomplete type 'sstables::sstable'
[2023-03-09T15:55:52.426Z]             if (!_sstable_runs_contributing_backlog.contains(crp.first->run_identifier())) {
[2023-03-09T15:55:52.426Z]                                                                       ^
```

Since there is no need to inline the backlog controller
code anyhow just move the implementation out of line.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>